website:
  title: "Alexandro Disla"
  description: "Statistics | Data Analyst | Backend Engineering"
  image: img/ad0791_profile.jpeg
  favicon: img/favicon.png
  back-to-top-navigation: true
  navbar:
    title: false
    background: "#355C7D"
    reader-mode: true
    pinned: false
    logo: /img/logo.png
    right:
      - icon: folder-symlink
        text: "My Projects"
        menu:
          - text: "Projects"
            href: projects/index.qmd
          - text: "Photography"
            href: photography/index.qmd
          - text: "CV"
            href: cv/index.qmd
      - icon: envelope
        aria-label: email
        href: "mailto:alexandrodisla@hotmail.com"
      - icon: linkedin
        aria-label: Linkedin
        href: https://www.linkedin.com/in/alexandro-disla-98160994/
      - icon: github
        aria-label: Github
        href: https://github.com/AD0791
      - icon: person-vcard
        aria-label: Upwork
        href: https://www.upwork.com/freelancers/~014d169b1fa2529359?viewMode=1
  search:
    location: navbar
    type: textbox
    copy-button: true
  page-footer:
    right: |
      <span class="faux-block">&#169; 2023 Alexandro Disla</span>

project:
  type: website
  output-dir: docs
  preview:
    port: 8013
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme:
      light: flatly
      dark: darkly
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
